# City name
city: Washington, DC, USA
# City centerpoint latitude & longitude
city_latitude: 38.9071923
city_longitude: -77.0368707
timezone: America/New_York
# Radius of city's road network from centerpoint in km (required if OSM has no polygon data)
city_radius: 25
# The folder under data where this city's data is stored
name: dc
# If given, limit crashes to after startdate and no later than enddate
# Recommended to limit to just a few years for now
startdate: 2014-01-01
enddate: 2016-12-31
# The type of predictions to generate, 'segment' is default, 'week' is legacy
level: 'segment'

#################################################################
# Configuration for data standardization

# crash file configurations
crashes_files:
  Crashes_in_DC.csv:
    required:
      id: OBJECTID
      latitude: Y
      longitude: X
      # If date supplied in single column:
      date_complete: REPORTDATE
      # If date is separated into year/month/day:
      date_year: 
      date_month: 
      # Leave date_day empty if not available
      date_day: 
      # If time is available and separate from date:
      time: 
      # If time specified, time_format is one of:
      # default (HH:MM:SS)
      # seconds (since midnight)
      # military (HHMM)
      time_format: 
    optional:
      summary: MAR_ADDRESS
      vehicles: TOTAL_VEHICLES
      bikes: TOTAL_BICYCLES

# List of concern type information
concern_files:
  - name: concern
    filename: Vision_Zero_Safety.csv
    latitude: Y
    longitude: X
    time: REQUESTDATE


# week on which to predict crashes (week, year)
# Best practice is to choose a week towards the end of your crash data set
# in format [month, year]
time_target: [51, 2016]
# specify how many weeks back to predict in output of train_model
weeks_back: 1
